name: No Response

# **What it does**: Closes issues that don't have enough information to be
#                   actionable.
# **Why we have it**: To remove the need for maintainers to remember to check
#                     back on issues periodically to see if contributors have
#                     responded.
# **Who does it impact**: Everyone that works on docs or docs-internal.

on:
  issue_comment:
    types: [created]

  schedule:
    - cron: '20 * * * *' # Run each hour at 20 minutes past

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  noResponse:
    runs-on: ubuntu-latest
    if: github.repository == 'github/docs'
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          only-labels: 'more-information-needed'
          days-before-stale: -1
          days-before-issue-stale: 14
          days-before-close: -1
          days-before-issue-close: 0
          close-issue-message: >
            This issue has been automatically closed because there has been no response
            to our request for more information from the original author. With only the
            information that is currently in the issue, we don't have enough information
            to take action. Please reach out if you have or find the answers we need so
            that we can investigate further. See [this blog post on bug reports and the
            importance of repro steps](https://www.lee-dohm.com/2015/01/04/writing-good-bug-reports/)
            for more information about the kind of information that may be helpful.
          days-before-pr-stale: 7
          days-before-pr-close: 0
          close-pr-message: >
            This PR has been automatically closed because there has been no response to
            to our request for more information from the original author. Please reach out
            if you have the information we requested, or open a [new issue](https://github.com/github/docs/issues/new/choose)
            to describing your changes. Then we can begin the review process.

      - name: Check out repo
        if: ${{ failure() }}
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/slack-alert
        if: ${{ failure() }}
        with:
          slack_channel_id: ${{ secrets.DOCS_ALERTS_SLACK_CHANNEL_ID }}
          slack_token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
.github/workflows/no-response.yaml
            - name: Upload a Build Artifact
  uses: actions/upload-artifact@v4.3.4
  with:
    # Artifact name
    name: # optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
    path: 
    # The desired behavior if no files are found using the provided path.
Available Options:
  warn: Output a warning but do not fail the action
  error: Fail the action with an error message
  ignore: Do not output any warnings or errors, the action does not fail

    if-no-files-found: # optional, default is warn
    # Duration after which artifact will expire in days. 0 means using default retention.
Minimum 1 day. Maximum 90 days unless changed from the repository settings page.

    retention-days: # optional
    # The level of compression for Zlib to be applied to the artifact archive. The value can range from 0 to 9: - 0: No compression - 1: Best speed - 6: Default compression (same as GNU Gzip) - 9: Best compression Higher levels will result in better compression, but will take longer to complete. For large files that are not easily compressed, a value of 0 is recommended for significantly faster uploads.

    compression-level: # optional, default is 6
    # If true, an artifact with a matching name will be deleted before a new one is uploaded. If false, the action will fail if an artifact for the given name already exists. Does not fail if the artifact does not exist.

    overwrite: # optional, default is false            - name: Upload a Build Artifact
  uses: actions/upload-artifact@v4.3.4
  with:
    # Artifact name
    name: # optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
    path: 
    # The desired behavior if no files are found using the provided path.
Available Options:
  warn: Output a warning but do not fail the action
  error: Fail the action with an error message
  ignore: Do not output any warnings or errors, the action does not fail

    if-no-files-found: # optional, default is warn
    # Duration after which artifact will expire in days. 0 means using default retention.
Minimum 1 day. Maximum 90 days unless changed from the repository settings page.

    retention-days: # optional
    # The level of compression for Zlib to be applied to the artifact archive. The value can range from 0 to 9: - 0: No compression - 1: Best speed - 6: Default compression (same as GNU Gzip) - 9: Best compression Higher levels will result in better compression, but will take longer to complete. For large files that are not easily compressed, a value of 0 is recommended for significantly faster uploads.

    compression-level: # optional, default is 6
    # If true, an artifact with a matching name will be deleted before a new one is uploaded. If false, the action will fail if an artifact for the given name already exists. Does not fail if the artifact does not exist.

    overwrite: # optional, default is false
          
          
